# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-qt6'
    'frameworks/karchive': 'Frameworks/6.24'
    'frameworks/kauth': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kdoctools': 'Frameworks/6.24'
    'frameworks/kfilemetadata': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kjobwidgets': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/knewstuff': 'Frameworks/6.24'
    'frameworks/knotifyconfig': 'Frameworks/6.24'
    'frameworks/solid': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'multimedia/libkcddb': '@same'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
