/* config-k3b.h. Generated by cmake from config-k3b.h.cmake */

#cmakedefine K3B_DEBUG

#cmakedefine ENABLE_DVD_RIPPING

#cmakedefine ENABLE_TAGLIB

#cmakedefine HAVE_SYS_VFS_H

#cmakedefine HAVE_SYS_STATVFS_H

#cmakedefine HAVE_STAT64

#define K3B_VERSION_STRING "${K3B_VERSION_STRING}"

#cmakedefine ENABLE_HAL_SUPPORT

#cmakedefine ENABLE_AUDIO_PLAYER

#cmakedefine HAVE_BYTESWAP_H

#cmakedefine WORDS_BIGENDIAN

#cmakedefine HAVE_ICONV
#cmakedefine ICONV_SECOND_ARGUMENT_IS_CONST

#cmakedefine HAVE_FSTAB_H

#cmakedefine HAVE_FFMPEG_AVFORMAT_OPEN_INPUT
#cmakedefine HAVE_FFMPEG_AV_DUMP_FORMAT
#cmakedefine HAVE_FFMPEG_AVFORMAT_FIND_STREAM_INFO
#cmakedefine HAVE_FFMPEG_AVFORMAT_CLOSE_INPUT
#cmakedefine HAVE_FFMPEG_AVCODEC_OPEN2
#cmakedefine HAVE_FFMPEG_AVCODEC_DECODE_AUDIO4
#cmakedefine HAVE_FFMPEG_AVMEDIA_TYPE
#cmakedefine HAVE_FFMPEG_CODEC_MP3
