/* config-k3b.h. Generated by cmake from config-k3b.h.cmake */
#cmakedefine K3B_DEBUG 1

#cmakedefine HAVE_MUSICBRAINZ 1

#define SIZEOF_INT ${SIZEOF_INT}

#define SIZEOF_LONG ${SIZEOF_LONG}

#cmakedefine HAVE_LRINT 1

#cmakedefine HAVE_LRINTF 1

#cmakedefine HAVE_SYS_VFS_H 1

#cmakedefine HAVE_SYS_STATVFS_H 1

#cmakedefine HAVE_STAT64 1

#define K3B_VERSION_STRING "${K3B_VERSION_STRING}"
