/* config-k3b.h. Generated by cmake from config-k3b.h.cmake */
#cmakedefine K3B_DEBUG 1

#cmakedefine HAVE_MUSICBRAINZ

#cmakedefine HAVE_LIBDVDREAD

#define SIZEOF_INT ${SIZEOF_INT}

#define SIZEOF_LONG ${SIZEOF_LONG}

#cmakedefine HAVE_SYS_VFS_H 1

#cmakedefine HAVE_SYS_STATVFS_H 1

#cmakedefine HAVE_STAT64 1

#define K3B_VERSION_STRING "${K3B_VERSION_STRING}"

#cmakedefine HAVE_K3BSETUP 1

#cmakedefine HAVE_TAGLIB 1
