# SPDX-FileCopyrightText: 2024, 2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: k3b
confinement: strict
grade: stable
base: core24
adopt-info: k3b
apps:
  k3b:
    extensions:
      - kde-neon-6
    common-id: org.kde.k3b.desktop
    desktop: usr/share/applications/org.kde.k3b.desktop
    command: usr/bin/k3b
    plugs:
      - audio-record
      - browser-support
      - home
      - optical-drive
      - mount-observe
      - system-backup
      - udisks2
      - removable-media
      - hardware-observe
      - raw-usb
    environment:
      QTWEBENGINE_DISABLE_SANDBOX: 1
      LD_LIBRARY_PATH: "$SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH"
      PATH: $SNAP/ffmpeg-platform/usr/bin:$SNAP/usr/bin:$PATH
      ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
      QT_MEDIA_BACKEND: "ffmpeg"
plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform # the folder where this content snap will be mounted
    default-provider: ffmpeg-2404
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.k3b
    bus: session
package-repositories:
  - type: apt
    components:
      - main
    suites:
      - noble
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
  libkcddb:
    source: https://invent.kde.org/multimedia/libkcddb.git
    source-branch: master
    stage-packages:
      - rsync
      - libpopt0
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
      - -DCMAKE_FIND_ROOT_PATH="$CRAFT_STAGE;/snap/kde-qt6-core24-sdk/current;/snap/kf6-core24-sdk/current"
    build-environment:
      - PKG_CONFIG_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig"
      - LD_LIBRARY_PATH: "${LD_LIBRARY_PATH}:$CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR"
    override-build: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  k3b:
    after:
      - libkcddb
    parse-info:
      - usr/share/metainfo/org.kde.k3b.appdata.xml
    plugin: cmake
    build-packages:
      - libavformat-dev
      - libdvdread-dev
      - libflac++-dev
      - libflac-dev
      - libfuzzer-14-dev
      - libkcddb6-dev
      - libmad0-dev
      - libmp3lame-dev
      - libmpcdec-dev
      - libmusicbrainz5-dev
      - libsamplerate0-dev
      - libsndfile1-dev
      - libtag1-dev
      - libvorbis-dev
      - libpulse0
    build-snaps:
      - ffmpeg-2404-sdk
    stage-packages:
      - cdparanoia
      - cdrdao
      - cdrskin
      - dvd+rw-tools
      - genisoimage
      - growisofs
      - libdvdread8t64
      - libflac++10
      - libneon27t64-gnutls
      - libmusicbrainz5cc2v5
      - normalize-audio
      - sox
      - udisks2
      - vcdimager
      - wodim
      - libpulse0
    source: .
    source-type: local
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    build-environment: &buildenvironment
      - PATH: /snap/kde-qt6-core24-sdk/current/usr/bin${PATH:+:$PATH}
      - PKG_CONFIG_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kde-qt6-core24-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
      - XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kde-qt6-core24-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
      - LD_LIBRARY_PATH: "/snap/kde-qt6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/kde-qt6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libproxy:/snap/kde-qt6-core24-sdk/current/usr/lib:/snap/kf6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/kf6-core24-sdk/current/usr/lib:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/:$CRAFT_STAGE/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      - PYTHONPATH: ${CRAFT_STAGE}/lib/python3.12/site-packages:${CRAFT_STAGE}/usr/lib/python3/dist-packages
      - DICPATH: "$SNAP/usr/share/hunspell"
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [k3b]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - k3b
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
      - ffmpeg-2404
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24" "ffmpg-2404"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done

