/***************************************************************************
                          k3bcddacopy.cpp  -  description
                             -------------------
    begin                : Sun Nov 4 2001
    copyright            : (C) 2001 by Sebastian Trueg
    email                : trueg@informatik.uni-freiburg.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/


#include "../tools/k3bglobals.h"
#include "k3bcdda.h"
#include "k3bcddacopy.h"
#include "k3bcdview.h"
#include "k3bripperwidget.h"
#include "../device/k3bdevice.h"

#include <qptrlist.h>
#include <qstringlist.h>
#include <qstring.h>
#include <qtimer.h>

#include <klocale.h>
#include <kio/global.h>
#include <kdebug.h>

void paranoiaCallback(long, int){
  // Do we want to show info somewhere ?
  // Not yet.
}


K3bCddaCopy::K3bCddaCopy( QObject* parent ) 
  : K3bJob( parent )
{
  m_device = 0;
}

K3bCddaCopy::~K3bCddaCopy()
{
}

void K3bCddaCopy::start()
{
  // TODO: check for m_device == 0
  // TODO: prepare directories
  // TODO: get correct fileanames from Parser
  // TODO: save in Songdb (only if ripping to wave)

  //bool result = true;
  m_bytesAll = 0;
  m_interrupt = false;
  kdDebug() << "(K3bCddaCopy) Start copying " << m_bytes << "d" << endl;
  m_drive = m_device->open();
  emit started();
  emit newTask( i18n("Copy cdrom ")  );
  infoMessage( i18n("Copying started."), STATUS);
  if( !startRip( m_currentTrackIndex=0 ) )
    emit finished( false );
}

bool K3bCddaCopy::startRip(int i){
    infoMessage( i18n("Copy track: ") + QString::number(m_tracksToCopy[i]) + i18n(" to ") + KIO::decodeFileName( m_list[i] ), PROCESS);
    if( !paranoiaRead( m_drive, m_tracksToCopy[i], m_list[i] ))
        return false;
    return true;
}

void K3bCddaCopy::finishedRip(){
    kdDebug() << "(K3bCddaCopy) Finished copying." << endl;
    infoMessage( "Copying finished.", STATUS);
    m_device->close();
    kdDebug() << "(K3bCddaCopy) Exit." << endl;
   emit finished( true );
}


void K3bCddaCopy::cancel( ){
    m_interrupt = true;
}


// this is to use with audiocd-kio-slave:
// "audiocd:/" + i18n("By Track") + "/" + i18n("Track") + QString::number(no).rightJustify( '0', 2 ) + "?device=" + m_device->ioctlDevice()
// "audiocd:/" + "MP3" + "/" + QString::number(no).rightJustify( '0', 2 ) + "*" + "?device=" + m_device->ioctlDevice()
// "audiocd:/" + "Ogg Vorbis" + "/" + QString::number(no).rightJustify( '0', 2 ) + "?device=" + m_device->ioctlDevice()

// KIO::copy( url, destWithK3bPattern )
// only problem: mp3- and ogg-tags will be generated by audiocd-slave (mp3 is no problem via id3lib, what about ogg?)


bool K3bCddaCopy::paranoiaRead(struct cdrom_drive *drive, int track, QString dest){
    long firstSector = cdda_track_firstsector(drive, track);
    m_lastSector = cdda_track_lastsector(drive, track);
    // track length
    m_byteCount =  CD_FRAMESIZE_RAW * (m_lastSector - firstSector);
    m_trackBytesAll = 0;

    kdDebug() << "(K3bCddaCopy) paranoia_init" << endl;
    m_paranoia = paranoia_init(drive);

    if (0 == m_paranoia){
        infoMessage( i18n("paranoia_init failed."), ERROR);
        kdDebug() << "(K3bCddaCopy) paranoia_init failed" << endl;
        return false;
    }

    int paranoiaLevel = PARANOIA_MODE_FULL ^ PARANOIA_MODE_NEVERSKIP;
    paranoia_modeset(m_paranoia, paranoiaLevel);

    cdda_verbose_set(drive, CDDA_MESSAGE_PRINTIT, CDDA_MESSAGE_PRINTIT);

    paranoia_seek(m_paranoia, firstSector, SEEK_SET);
    m_currentSector = firstSector;

    kdDebug() << "(K3bCddaCopy) open files" << endl;

    // create wave file
    m_currentWrittenFile = dest;
    bool isOpen = m_waveFileWriter.open( dest );

    if( !isOpen ){
        infoMessage( i18n("Couldn't rip to: ") + dest, ERROR );
	m_currentWrittenFile = QString::null;
        paranoia_free(m_paranoia);
        m_paranoia = 0;
        finishedRip();
        m_interrupt = true;
        return false;
    }

    emit newSubTask( i18n("Copy ") + dest  );

    t = new QTimer( this );
    connect( t, SIGNAL(timeout()), SLOT(slotReadData()) );
    t->start( 0, FALSE );
    return true;
}

void K3bCddaCopy::readDataFinished(){
    m_waveFileWriter.close();
    if( m_interrupt ) {
        infoMessage( i18n("Interrupted by user"), STATUS);
        kdDebug() << "(K3bCddaCopy) Interrupted by user!" << endl;
        if( !QFile::remove( m_currentWrittenFile ) ){
            infoMessage( i18n("Can't delete part of copied file."), ERROR);
            kdDebug() << "(K3bCddaCopy) Can't delete copied file <>." << endl;
        }
    }
    m_currentWrittenFile = QString::null;

    paranoia_free(m_paranoia);
    m_paranoia = 0;
    ++m_currentTrackIndex;
    kdDebug() << "(K3bCddaCopy) Check index: " << m_currentTrackIndex << ", " << m_count << endl;
    if( (m_currentTrackIndex < m_count) && !m_interrupt ){
        startRip( m_currentTrackIndex );
    } else
        finishedRip();
}

void K3bCddaCopy::slotReadData(){

    if( m_interrupt){
        infoMessage( i18n("Interrupt reading."), PROCESS);
        kdDebug() << "(K3bCddaCopy) Interrupt reading." << endl;
        t->stop();
        readDataFinished();
    } else {
        int16_t * buf = paranoia_read(m_paranoia, paranoiaCallback);

        if (0 == buf) {
            infoMessage( i18n("Unrecoverable error in paranoia_read."), ERROR);
            kdDebug() << "(K3bCddaCopy) Unrecoverable error in paranoia_read" << endl;
        } else {
            ++m_currentSector;
	    m_waveFileWriter.write( (char*)buf, CD_FRAMESIZE_RAW, K3bWaveFileWriter::LittleEndian );
        }

      m_bytesAll += CD_FRAMESIZE_RAW;
      m_trackBytesAll += CD_FRAMESIZE_RAW;
      m_progressBarValue = (int) ((((double) m_bytesAll / (double) m_bytes ) * 100)+0.5);
      int trackProgressBarValue = (int) ((((double) m_trackBytesAll / (double) m_byteCount ) * 100)+0.5);

      if( m_progressBarValue > 100)
           m_progressBarValue=100;
      emit percent( m_progressBarValue );
      emit subPercent( trackProgressBarValue );

        if (m_currentSector < m_lastSector)
            t->start(0, FALSE);
        else {
            t->stop();
            readDataFinished();
        }
    }
} // end while sector check


#include "k3bcddacopy.moc"

